-- Copyright (C) 2026 CRM-RCV
--
-- Drop table for module uninstallation
-- NOTA: No borramos la tabla de etiquetas para preservar los datos
-- Si realmente necesitas eliminarla, ejecuta manualmente:
-- DROP TABLE IF EXISTS llx_cabinetmedfix_doc_labels;
